name: Firebase Deploy

on:
   push:
      branches:
         - main

jobs:
   build:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Setup Node.js
           uses: actions/setup-node@v4
           with:
              node-version: '20'

         - name: Install dependencies
           run: npm install

         - name: Build project
           run: npm run build

         - name: Install firebase CLI
           run: npm install -g firebase-tools

         - name: Deploy using firebase hosting
           run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_AUTH_TOKEN }} --project ${{ secrets.FIREBASE_PROJECT_ID }} --non-interactive

         # sebenarnya tidak perlu melakukan initialisasi untuk project ini
         # karena kita tidak memerlukan pemanggilan API dari front-end
         - name: Initialize Firebase app
           run: |
              echo "Initializing Firebase app"
              node -e "
                const { initializeApp } = require('firebase/app');
                const firebaseConfig = {
                  apiKey: '${{ secrets.FIREBASE_API_KEY }}',
                  authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}',
                  projectId: '${{ secrets.FIREBASE_PROJECT_ID }}',
                  storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}',
                  messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}',
                  appId: '${{ secrets.FIREBASE_APP_ID }}'
                };
                initializeApp(firebaseConfig);
              "
